### ISSUE TITLE
调用Rust编写的PetPet生成器，以提升性能 & 修复GIF偶尔会闪黑色

### ISSUE THREAD

**Issue by mokurin000** [Rosemoe/BotPlugin#14]
https://github.com/poly000/petpet-rs

目前缓存管理还没有做，而且我需要再做一个面向QQ号的Petpet生成包装

性能测试的话…… Kotlin咱不懂 也不会编写测试

- [x] Rust包: 导出为[jni](https://github.com/poly000/petpet-rs-jni)
- [ ] Kotlin: 调用Rust，JNI

**Comment by Rosemoe** [comment]
我中午看看现在性能怎么样

**Comment by mokurin000** [comment]
> 我中午看看现在性能怎么样

那我先去测一下Rust版本的性能，speed用30，因为这个大小看不出来speed设为1或者30的差异……

随便找了张用户头像，在tmpfs中 100次生成需要3.31s
```bash
./bench avatar.jpg avatar30.gif 30  3.31s user 0.12s system 100% cpu 3.415 total
```

**Comment by Rosemoe** [comment]
你要从JVM调用程序测试

**Comment by poly000** [comment]
> 你要从JVM调用程序测试

emm 我去找找怎么调FFI……

**Comment by Rosemoe** [comment]
Runtime.getRuntime().exec()可以执行命令

**Comment by mokurin000** [comment]
> Runtime.getRuntime().exec()可以执行命令

<del>调Shell有点慢了吧…… FFI可以更快</del>

仔细一想调shell + 启动Rust 的开销并没有编码那么大。。

**Comment by mokurin000** [comment]
刚刚注意到Petpet的NewQuant使用10作为sample...
```bash
time for i in {1..1000};do ./target/release/petpet test.png test.gif 10;done
```
||耗时|
|-------|------|
real	|1m6.847s
user	|0m38.450s
sys	|0m10.634s

**Comment by mokurin000** [comment]
顺便现在不知道为什么可能会出现黑屏…… 这算是顺便的bugfix

**Comment by Rosemoe** [comment]
![image](https://user-images.githubusercontent.com/28822819/128663517-c1ee0d4f-2ebd-48b8-b658-9679f6c7b111.png)
我的U事i3-9100F

**Comment by Rosemoe** [comment]
直接JVM实现就行了。Shell调用外部程序开销挺大的

**Comment by Rosemoe** [comment]
而且Mirai事多线程的，分发出去会低于15s

**Comment by mokurin000** [comment]
> 直接JVM实现就行了。Shell调用外部程序开销挺大的

```bash
./bin/app  3.89s user 1.13s system 327% cpu 1.535 total
```
我的u是i5-8500... 可以把这个Test.kt发一下吗

```java
package TestRustCallPerformance;

public class App {
    public static void main(String[] args) {
        try {
			for (int i=0; i<1000; ++i)
				Runtime.getRuntime().exec("./petpet test.png test.gif 10").waitFor();
		} catch (Exception e) {
			
   	 	}
	}
}


```
看样子bash的for循环开销有点大……

**Comment by Rosemoe** [comment]
你对方法的理解有问题。
Rutnime.getRuntime().exec()事**启动一个进程**而不会等待进程结束
这一操作不会阻塞当前线程。使用该方法返回的Process对象waitFor()来等待进程结束并得到exitCode

**Comment by poly000** [comment]
> 你对方法的理解有问题。
> Rutnime.getRuntime().exec()事**启动一个进程**而不会等待进程结束
> 这一操作不会阻塞当前线程。使用该方法返回的Process对象waitFor()来等待进程结束并得到exitCode

啊这

**Comment by Rosemoe** [comment]
啊这，我电脑关了（

**Comment by mokurin000** [comment]
> 啊这，我电脑关了（

（

**Comment by Rosemoe** [comment]
[Test.txt](https://github.com/Rosemoe/BotPlugin/files/6952389/Test.txt)
后缀自己改下（（（

**Comment by mokurin000** [comment]
> [Test.txt](https://github.com/Rosemoe/BotPlugin/files/6952389/Test.txt)
> 后缀自己改下（（（

感觉Shell的开销相较于NeuQuanty的开销不值一提（如果sample小于15左右，你这里用的好像是10）

其实没必要完全RIIR，如果NeuQuanty调用FFI就足够快了（至少在我基于image-rs的版本是分析这个生成占cpu时间最长）

**Comment by Rosemoe** [comment]
我要上学先溜了，晚上回来再check
我不清楚gif的合成，也没配置过sample
gifmaker从github上随便找的

**Comment by mokurin000** [comment]
> 我要上学先溜了，晚上回来再check
> 我不清楚gif的合成，也没配置过sample
> gifmaker从github上随便找的

啊这。。。 我试过，sample是30时这个大小也看不出来有什么质量差异，但是速度比10提升了十几倍

**Comment by Rosemoe** [comment]
离开当前语言到其他语言开销还是比较大的，甚至包括Java字节码到native code

**Comment by mokurin000** [comment]
> 离开当前语言到其他语言开销还是比较大的，甚至包括Java字节码到native code

那我先跑次Kotlin的bench吧…… （FFI的话应该开销比创建shell要小一点）
如果在kotlin版本修改sample的值倒也能带来很大提升，但是我觉得这个交给用户配置比较好

https://doc.servo.org/color_quant/struct.NeuQuant.html#method.new 这里解释了Sample参数

**Comment by Rosemoe** [comment]
> > 直接JVM实现就行了。Shell调用外部程序开销挺大的
> 
> ```shell
> ./bin/app  3.89s user 1.13s system 327% cpu 1.535 total
> ```
> 
> 我的u是i5-8500... 可以把这个Test.kt发一下吗
> 
> ```java
> package TestRustCallPerformance;
> 
> public class App {
>     public static void main(String[] args) {
>         try {
> 			for (int i=0; i<1000; ++i)
> 				Runtime.getRuntime().exec("./petpet test.png test.gif 10").waitFor();
> 		} catch (Exception e) {
> 			
>    	 	}
> 	}
> }
> ```
> 
> 看样子bash的for循环开销有点大……

二进制文件发我看看

**Comment by mokurin000** [comment]
> > > 直接JVM实现就行了。Shell调用外部程序开销挺大的
> > 
> > 
> > ```shell
> > ./bin/app  3.89s user 1.13s system 327% cpu 1.535 total
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的u是i5-8500... 可以把这个Test.kt发一下吗
> > ```java
> > package TestRustCallPerformance;
> > 
> > public class App {
> >     public static void main(String[] args) {
> >         try {
> > 			for (int i=0; i<1000; ++i)
> > 				Runtime.getRuntime().exec("./petpet test.png test.gif 10").waitFor();
> > 		} catch (Exception e) {
> > 			
> >    	 	}
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看样子bash的for循环开销有点大……
> 
> 二进制文件发我看看

Windows的吗

**Comment by Rosemoe** [comment]
草 两点了 先溜了

**Comment by mokurin000** [comment]
> 草 两点了 先溜了

（ 我也要上网课了

二进制下载在这里 https://github.com/poly000/petpet-rs/releases/tag/v1.0.0
resource是必要的

**Comment by mokurin000** [comment]
![image](https://user-images.githubusercontent.com/34085039/128673381-23a575e1-e0fc-43af-b0a9-6766249148bc.png)
对比了一下speed=1 和 speed=10

如果缩放100%大概很难看出差距

不过用 Rust 版本可以在 `speed=1` 时达到可以接受的性能

**Comment by Rosemoe** [comment]
> > 直接JVM实现就行了。Shell调用外部程序开销挺大的
> 
> ```shell
> ./bin/app  3.89s user 1.13s system 327% cpu 1.535 total
> ```
> 
> 我的u是i5-8500... 可以把这个Test.kt发一下吗
> 
> ```java
> package TestRustCallPerformance;
> 
> public class App {
>     public static void main(String[] args) {
>         try {
> 			for (int i=0; i<1000; ++i)
> 				Runtime.getRuntime().exec("./petpet test.png test.gif 10").waitFor();
> 		} catch (Exception e) {
> 			
>    	 	}
> 	}
> }
> ```
> 
> 看样子bash的for循环开销有点大……


不要生吞异常
e.printStackTrace();
打印exitCode
看看

**Comment by mokurin000** [comment]
> e.printStackTrace();

我好像改1000次时没有重新build草
结果1000次需要37s...

**Comment by poly000** [comment]
我去做一下面向JNI的库再试试？JNI性能可能会比创建自shell好很多

**Comment by poly000** [comment]
我去做一下面向JNI的库再试试？JNI性能可能会比创建自shell好很多

**Comment by mokurin000** [comment]
写好JNI的了： https://github.com/poly000/petpet-rs-jni

**Comment by Rosemoe** [comment]
你试下性能，我还要写私人bot（（（
如果没问题pr我

**Comment by Rosemoe** [comment]
> > e.printStackTrace();
> 
> 我好像改1000次时没有重新build草
> 结果1000次需要37s...

草

**Comment by Rosemoe** [comment]
突然想到一个问题，用native的话多平台有点麻烦（（（
你用的是linux吧，我用的是Windows

**Comment by mokurin000** [comment]
> 突然想到一个问题，用native的话多平台有点麻烦（（（
> 你用的是linux吧，我用的是Windows

不同平台用CI构建分别的lib就行了
<del>（话说JNI要怎么调用）</del>

**Comment by Rosemoe** [comment]
我本来就没用过jni开发

**Comment by mokurin000** [comment]
> 我本来就没用过jni开发

听arch群群友说JNI是最快的调用方法
然而我不会写java/kotlin（没有任何经验）……

我可以翻文档糊一个bench程序，但是改PetPet，移除废弃的库我就完全做不好……

**Comment by Rosemoe** [comment]
我也不会jni（（（
当然如果你能整个Java入口方法后面改kotlin可以我来

**Comment by poly000** [comment]
> 我也不会jni（（（
> 当然如果你能整个Java入口方法后面改kotlin可以我来

应该可以直接用Java方法？（ Kotlin好像是和java完全兼容的

**Comment by poly000** [comment]
> 我也不会jni（（（
> 当然如果你能整个Java入口方法后面改kotlin可以我来

https://github.com/poly000/petpet-rs-jni/releases/tag/test

**Comment by mokurin000** [comment]
> 我也不会jni（（（
> 当然如果你能整个Java入口方法后面改kotlin可以我来


结果是 
```
./bin/app  40.91s user 0.60s system 99% cpu 41.624 total
```
（1000次迭代，speed=10）
我直接Rust程序内迭代1000次需要
```
./bench test.png test.gif 10  41.01s user 0.50s system 99% cpu 41.662 total
```
性能差不多……

可以把Kotlin版本的测试用的jar包发给我吗……
虽然我觉得Rust版应该快很多

**Comment by mokurin000** [comment]
# JNI生成方法

## 首先写这个类

```java
class Petpet {
    public static native void GeneratePetpetToFile(String image, String gif, int speed);

    static {
        System.loadLibrary("petpet_jni");
    }
}
```

## 然后生成对应函数名

```bash
javac -h <path to the source code>
```
得到一个`.h`文件，其中的函数名需要改到Rust。（你放进去后记得告诉我函数名，我改一下）

## 放好库

这个平台相关，需要用户操作……

**Comment by poly000** [comment]
现在我写的是void…… 明天我准备改成 jboolean ，仅判断是否生成成功
现在如果出错会由Rust panic（这样应该不行，Bot是要持续运行的……）
你觉得错误反馈要怎么写好？

**Comment by poly000** [comment]
刚刚把CI加好了，就差改名 & 提升错误处理 了。
目前构建的有 `x86_64-unknown-linux-gnu` `x86_64-pc-windows-msvc` `x86_64-apple-darwin`

**Comment by mokurin000** [comment]
moved to issue #20
