### ISSUE TITLE
错误的图片格式

### ISSUE THREAD

**Issue by mokurin000** [Rosemoe/BotPlugin#16]
本地存储的用户头像是 jpeg格式，却带有png 后缀……

**Comment by Rosemoe** [comment]
其实图片格式怎么样都无所谓的。后缀不加都可以。

**Comment by mokurin000** [comment]
> 其实图片格式怎么样都无所谓的。后缀不加都可以。

这个主要是关系到 #14
我没有给petpet加手动判断图片类型（

**Comment by Rosemoe** [comment]
读文件头判断格式就好
