### ISSUE TITLE
[功能请求]可配置或关闭的 help 信息

### ISSUE THREAD

**Issue by 10935336** [Rosemoe/BotPlugin#7]
**Describe**
让 `help` 命令可以配置或关闭。

**Why**
我正在运行很多 Mirai Console 插件，因此我的`/help`是自行编写的多插件命令集合，BotPlugin 的 `help` 信息使我不得不禁用 BotPlugin。
此外 BotPlugin 的功能是可关闭的，当前的`help`可能会包含无效信息。

**Comment by Rosemoe** [comment]
🉑
我可以让/help允许被关闭

**Comment by Rosemoe** [comment]
现在可以通过
settings disable Help
来关闭帮助
